<?php echo $this->doctype(); ?>

<html lang="pl">
  <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CI-'. $this->translate('Faktury'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
	
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
						->appendStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all')
                        ->appendStylesheet($this->basePath() . '/fonts/font-awesome/css/font-awesome.min.css')
                        ->appendStylesheet($this->basePath() . '/img/simple-line-icons/simple-line-icons.min.css')
                        ->appendStylesheet($this->basePath() . '/bootstrap/css/bootstrap.min.css')
                        ->appendStylesheet($this->basePath() . '/uniform/css/uniform.default.css')
                        ->appendStylesheet($this->basePath() . '/bootstrap-select/bootstrap-select.min.css')
                        ->appendStylesheet($this->basePath() . '/select2/select2.css')
                        ->appendStylesheet($this->basePath() . '/bootstrap-switch/css/bootstrap-switch.min.css')
                        ->appendStylesheet($this->basePath() . '/gritter/css/jquery.gritter.css')
                        ->appendStylesheet($this->basePath() . '/bootstrap-daterangepicker/daterangepicker-bs3.css')
                        ->appendStylesheet($this->basePath() . '/fullcalendar/fullcalendar.css')
                        ->appendStylesheet($this->basePath() . '/jqvmap/jqvmap/jqvmap.css')
                        ->appendStylesheet($this->basePath() . '/css/tasks.css')
                        ->appendStylesheet($this->basePath() . '/css/components.css')
                        ->appendStylesheet($this->basePath() . '/css/plugins.css')
                        ->appendStylesheet($this->basePath() . '/css/layout.css')
                        ->appendStylesheet($this->basePath() . '/css/themes/darkblue.css')
                        ->appendStylesheet($this->basePath() . '/bootstrap-datepicker/css/datepicker.css')
                        ->appendStylesheet($this->basePath() . '/bootstrap-toastr/toastr.min.css')
                        ->appendStylesheet($this->basePath() . '/css/custom.css');
        ?>
  </head>
  <body class="page-header-fixed page-quick-sidebar-over-content page-style-square"> 
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
	<!-- BEGIN HEADER INNER -->
	<div class="page-header-inner">
		<!-- BEGIN LOGO -->
		<div class="page-logo">
			<a href="<?php echo $this->url('home'); ?>">
			<img src="<?php echo $this->basePath().'/img/Codeinc-logo.png'; ?>" alt="logo" style="margin-top: 5px;"/>
			</a>
			<div class="menu-toggler sidebar-toggler hide">
				<!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
			</div>
		</div>
		<!-- END LOGO -->
		<!-- BEGIN RESPONSIVE MENU TOGGLER -->
		<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
		</a>
		<!-- END RESPONSIVE MENU TOGGLER -->
		<!-- BEGIN TOP NAVIGATION MENU -->
		<div class="top-menu">
			<ul class="nav navbar-nav pull-right">
                <li class="dropdown dropdown-language">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <img alt="" src="<?php echo $this->basePath().'/img/flags/pl.png'; ?>"><span class="langname"> PL </span><i class="fa fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-default">
                        <li>
                            <a href="javascript:;">
                                <img alt="" src="<?php echo $this->basePath().'/img/flags/us.png'; ?>"> US
                            </a>
                        </li>
                    </ul>
                </li>
				<!-- BEGIN USER LOGIN DROPDOWN -->
				<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
				<li class="dropdown dropdown-user">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
					<img alt="" class="img-circle" src="<?php echo $this->basePath().'/img/avatar.png'; ?>"/>
					<span class="username username-hide-on-mobile">
					Nick </span>
					<i class="fa fa-angle-down"></i>
					</a>
					<ul class="dropdown-menu dropdown-menu-default">
						<li>
							<a href="extra_profile.html">
							<i class="icon-user"></i> My Profile </a>
						</li>
						<li>
							<a href="page_calendar.html">
							<i class="icon-calendar"></i> My Calendar </a>
						</li>
						<li>
							<a href="inbox.html">
							<i class="icon-envelope-open"></i> My Inbox <span class="badge badge-danger">
							3 </span>
							</a>
						</li>
						<li>
							<a href="page_todo.html">
							<i class="icon-rocket"></i> My Tasks <span class="badge badge-success">
							7 </span>
							</a>
						</li>
						<li class="divider">
						</li>
						<li>
							<a href="extra_lock.html">
							<i class="icon-lock"></i> Lock Screen </a>
						</li>
						<li>
							<a href="login.html">
							<i class="icon-key"></i> Log Out </a>
						</li>
					</ul>
				</li>
				<!-- END USER LOGIN DROPDOWN -->
			</ul>
		</div>
		<!-- END TOP NAVIGATION MENU -->
	</div>
	<!-- END HEADER INNER -->
</div>
<!-- END HEADER -->
<div class="clearfix">
</div>
<!-- BEGIN CONTAINER -->
<div class="page-container">
	<!-- BEGIN SIDEBAR -->
	<div class="page-sidebar-wrapper">
		<div class="page-sidebar navbar-collapse collapse">
			<!-- BEGIN SIDEBAR MENU -->
			<ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
				<!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
				<li class="sidebar-toggler-wrapper">
					<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
					<div class="sidebar-toggler">
					</div>
					<!-- END SIDEBAR TOGGLER BUTTON -->
				</li>
				<!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
				<li class="sidebar-search-wrapper">
					<!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
					<!-- DOC: Apply "sidebar-search-bordered" class the below search form to have bordered search box -->
					<!-- DOC: Apply "sidebar-search-bordered sidebar-search-solid" class the below search form to have bordered & solid search box -->
					<form class="sidebar-search " action="extra_search.html" method="POST">
						<a href="javascript:;" class="remove">
						<i class="icon-close"></i>
						</a>
						<div class="input-group">
							<input type="text" class="form-control" placeholder="Szukaj...">
							<span class="input-group-btn">
							<a href="javascript:;" class="btn submit"><i class="icon-magnifier"></i></a>
							</span>
						</div>
					</form>
					<!-- END RESPONSIVE QUICK SEARCH FORM -->
				</li>
				<li <?php if($this->getControllerName() == 'base\Controller\Index' && $this->getActionName() == 'index') {echo 'class="start active open"';} ?>>
					<a href="<?php echo $this->url('home'); ?>">
					<i class="icon-home"></i>
					<span class="title">Strona główna</span>
					<span class="selected"></span>
					</a>
				</li>	
				<li <?php if($this->getControllerName() == 'base\Controller\Invoice') {echo 'class="start active open"';} ?>>
					<a href="javascript:;">
					<i class="icon-docs"></i>
					<span class="title">Faktury</span>
					<span class="arrow "></span>
					</a>
					<ul class="sub-menu last">
						<li <?php if($this->getControllerName() == 'base\Controller\Invoice' && $this->getActionName() == 'summary') {echo 'class="active"';} ?>>
							<a href="<?php echo $this->url('base/default', array('controller' => 'invoice', 'action' => 'summary')); ?>">
								<i class="icon-grid"></i>
								Wszystkie
							</a>
						</li>
						<li <?php if($this->getControllerName() == 'base\Controller\Invoice' && $this->getActionName() == 'new') {echo 'class="active"';} ?>>
							<a href="<?php echo $this->url('base/default', array('controller' => 'invoice', 'action' => 'new')); ?>">
								<i class="icon-doc"></i>
								Nowa faktura
							</a>
						</li>
					</ul>
				</li>
			</ul>
			<!-- END SIDEBAR MENU -->
		</div>
	</div>
	<!-- END SIDEBAR -->
	<!-- BEGIN CONTENT -->
	<div class="page-content-wrapper">
		<div class="page-content">
			<?php echo $this->content; ?>
		</div>
	</div>
	<!-- END CONTENT -->
</div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
<div class="page-footer">
	<div class="page-footer-inner">
		 2015 &copy; Codeinc
	</div>
	<div class="scroll-to-top">
		<i class="icon-arrow-up"></i>
	</div>
</div>
<!-- END FOOTER -->
<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
  
			
			<?php echo $this->inlineScript()
            	->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            	->prependFile($this->basePath() . '/js/excanvas.min.js',   'text/javascript', array('conditional' => 'lt IE 9',))
	            ->appendFile ( $this->basePath () . '/js/jquery-1.11.0.min.js' )
	            ->appendFile ( $this->basePath () . '/js/jquery-migrate.min.js' )
	            ->appendFile ( $this->basePath () . '/js/jquery-ui-1.10.3.custom.min.js' )
	            ->appendFile ( $this->basePath () . '/bootstrap/js/bootstrap.min.js' )
	            ->appendFile ( $this->basePath () . '/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js' )
	            ->appendFile ( $this->basePath () . '/js/jquery-slimscroll/jquery.slimscroll.min.js' )
	            ->appendFile ( $this->basePath () . '/js/jquery.blockui.min.js' )
	            ->appendFile ( $this->basePath () . '/js/jquery.cokie.min.js' )
	            ->appendFile ( $this->basePath () . '/uniform/jquery.uniform.min.js' )
	            ->appendFile ( $this->basePath () . '/bootstrap-switch/js/bootstrap-switch.min.js' )
	            ->appendFile ( $this->basePath () . '/flot/jquery.flot.min.js' )
	            ->appendFile ( $this->basePath () . '/flot/jquery.flot.resize.min.js' )
	            ->appendFile ( $this->basePath () . '/flot/jquery.flot.categories.min.js' )
	            ->appendFile ( $this->basePath () . '/js/jquery.pulsate.min.js' )
	            ->appendFile ( $this->basePath () . '/bootstrap-daterangepicker/moment.min.js' )
	            ->appendFile ( $this->basePath () . '/bootstrap-daterangepicker/daterangepicker.js' )
	            ->appendFile ( $this->basePath () . '/fullcalendar/fullcalendar.min.js' )
	            ->appendFile ( $this->basePath () . '/js/jquery-easypiechart/jquery.easypiechart.min.js' )
	            ->appendFile ( $this->basePath () . '/js/jquery.sparkline.min.js' )
	            ->appendFile ( $this->basePath () . '/gritter/js/jquery.gritter.js' )
	            ->appendFile ( $this->basePath () . '/js/metronic.js' )
	            ->appendFile ( $this->basePath () . '/js/layout.js' )
	            ->appendFile ( $this->basePath () . '/js/quick-sidebar.js' )
	            ->appendFile ( $this->basePath () . '/js/index.js' )
	            ->appendFile ( $this->basePath () . '/js/tasks.js' )
                ->appendFile ( $this->basePath () . '/bootstrap-datepicker/js/bootstrap-datepicker.js' )
                ->appendFile ( $this->basePath () . '/bootstrap-toastr/toastr.min.js' )
                ->appendFile ( $this->basePath () . '/js/components-pickers.js' )
                ->appendFile ( $this->basePath () . '/bootstrap-select/bootstrap-select.min.js' )
                ->appendFile ( $this->basePath () . '/bootstrap-confirmation/bootstrap-confirmation.min.js' )
                ->appendFile ( $this->basePath () . '/select2/select2.min.js' )
                ->appendFile ( $this->basePath () . '/select2/select2_locale_pl.js' )
                ->appendFile ( $this->basePath () . '/js/base/invoice/new.js' )
        	; ?>
			
			<script>
			jQuery(document).ready(function() {    
			   Metronic.init(); // init metronic core componets
			   Layout.init(); // init layout
			   QuickSidebar.init() // init quick sidebar
			   Index.init();   
			   Index.initDashboardDaterange();
			   Index.initCalendar(); // init index page's custom scripts
			   Index.initCharts(); // init index page's custom scripts
			   Index.initChat();
			   Index.initMiniCharts();
			   Tasks.initDashboardWidget();
               ComponentsPickers.init();

                var panel = $('.theme-panel');
                $('.toggler', panel).click(function() {
                    $('.toggler').hide();
                    $('.toggler-close').show();
                    $('.theme-panel > .theme-options').show();
                });

                $('.toggler-close', panel).click(function() {
                    $('.toggler').show();
                    $('.toggler-close').hide();
                    $('.theme-panel > .theme-options').hide();
                });
			});
			</script>
			<!-- END JAVASCRIPTS -->
  </body>
</html>
