<style>
    body {
        color: #333333;
        font-family: "Open Sans", sans-serif;
        padding: 0px !important;
        margin: 0px !important;
        font-size: 13px;
        direction: ltr;
    }
    b, strong {
        font-weight: 700;
    }
    .list-unstyled {
        padding-left: 0;
        list-style: none;
    }
    h1, h2, h3, h4, h5, h6 {
        font-family: "Open Sans", sans-serif;
        font-weight: 300;
    }
    h3 {
        font-size: 23px;
    }
    .table {
        width: 100%;
        max-width: 100%;
        margin-bottom: 20px;
        border-spacing: 0;
        border-collapse: collapse;
    }
    thead {
        display: table-header-group;
        vertical-align: middle;
        border-color: inherit;
    }
    th {
        text-align: left;
    }
    .table>caption+thead>tr:first-child>th, .table>colgroup+thead>tr:first-child>th, .table>thead:first-child>tr:first-child>th, .table>caption+thead>tr:first-child>td, .table>colgroup+thead>tr:first-child>td, .table>thead:first-child>tr:first-child>td {
        border-top: 0;
    }
    tbody {
        display: table-row-group;
        vertical-align: middle;
        border-color: inherit;
    }
    .table-striped>tbody>tr:nth-child(odd) {
        background-color: #f9f9f9;
    }
    .table>thead>tr>th, .table>tbody>tr>th, .table>tfoot>tr>th, .table>thead>tr>td, .table>tbody>tr>td, .table>tfoot>tr>td {
        padding: 8px;
        line-height: 1.42857143;
        vertical-align: top;
        border-top: 1px solid #ddd;
    }
    .col-xs-2 {
        width: 16.66666667%;
    }
    .col-xs-3 {
        width: 25%;
    }
    .col-xs-4 {
        width: 33.33333333%;
    }
    .col-xs-6 {
        width: 50%;
    }
    .col-xs-8 {
        width: 66.66666667%;
    }
    .col-xs-9 {
        width: 75%;
    }
    .col-xs-10 {
        width: 83.33333333%;
    }
    .col-xs-12 {
        width: 100%;
    }
    .col-xs-1, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9, .col-xs-10, .col-xs-11, .col-xs-12 {
        float: left;
    }

    .text-align-center {
        text-align: center !important;
    }
</style>
<div class="portlet light">
    <div class="portlet-body">
        <div class="invoice">
            <div class="row invoice-logo">
                <div class="col-xs-8 invoice-logo-space">
                    <img src="http://ci-invoice.dev/img/Codeinc-logo-invoice.png" class="img-responsive" alt=""/>
                </div>
                <div class="col-xs-4" style="text-align: right; padding-top: 3px; line-height: 5px;" >
                    <h4><strong>Data wystawienia:</strong> 01/01/2015</h4>
                    <h4><strong>Data sprzedaży:</strong> 01/01/2015</h4>
                    <h4><strong>Termin płatności:</strong> 01/01/2015</h4>
                </div>
            </div>
            <br style="clear: both;">
            <div class="row">
                <h1 style="text-align: center;">Faktura</h1>
                <h2 style="text-align: center;">0001/01/2015</h2>
                <h4 style="text-align: center;">ORYGINAŁ</h4>
            </div>
            <div class="row" style="margin-bottom: 30px;">
                <div class="col-xs-6">
                    <h4><strong>Sprzedawca:</strong></h4>
                    <ul class="list-unstyled" style="font-size: 14px;">
                        <li>Codeinc Marcin Walas</li>
                        <li>PROF. STEFANA GOLACHOWSKIEGO 18</li>
                        <li>45-842 Opole</li>
                        <li>NIP: 7542912497</li>
                        <li>mBank</li>
                        <li>26 1140 2004 0000 3102 7503 4616</li>
                    </ul>
                </div>
                <div class="col-xs-6">
                    <h4><strong>Nabywca:</strong></h4>
                    <ul class="list-unstyled" style="font-size: 14px;">
                        <li>Codeinc Marcin Walas</li>
                        <li>PROF. STEFANA GOLACHOWSKIEGO 18</li>
                        <li>45-842 Opole</li>
                        <li>NIP: 7542912497</li>
                        <li>mBank</li>
                        <li>26 1140 2004 0000 3102 7503 4616</li>
                    </ul>
                </div>
            </div>
            <br style="clear: both;">
            <br>
            <br>
            <div class="row">
                <div class="col-xs-12">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                Nazwa towaru/usługi
                            </th>
                            <th class="hidden-480">
                                Ilość
                            </th>
                            <th class="hidden-480">
                                Cena netto
                            </th>
                            <th class="hidden-480">
                                VAT %
                            </th>
                            <th class="hidden-480">
                                Wartość VAT
                            </th>
                            <th class="hidden-480">
                                Wartość netto
                            </th>
                            <th>
                                Wartość brutto
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                1
                            </td>
                            <td>
                                Hardware
                            </td>
                            <td class="hidden-480">
                                32
                            </td>
                            <td class="hidden-480">
                                $75
                            </td>
                            <td class="hidden-480">
                                $1800
                            </td>
                            <td class="hidden-480">
                                20
                            </td>
                            <td class="hidden-480">
                                $25
                            </td>
                            <td>
                                $2152
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <br style="clear: both;">
            <br>
            <div class="row">
                <div class="col-xs-6 invoice-block">
                    <ul class="list-unstyled amounts">
                        <li>
                            <strong>Wartość netto:</strong> $9265
                        </li>
                        <li>
                            <strong>Wartość VAT:</strong> 20%
                        </li>
                        <li>
                            <strong>Wartość brutto:</strong> $12489
                        </li>
                    </ul>
                </div>
                <div class="col-xs-6" style="text-align: right;">
                    <ul class="list-unstyled amounts">
                        <li>
                            <h3><strong>Do zapłaty:</strong> $9265</h3>
                        </li>
                    </ul>
                </div>
            </div>
            <br style="clear: both;">
            <br>
            <br>
            <hr>
            <div class="row">
                <div class="col-xs-12 invoice-block">
                    <ul class="list-unstyled amounts">
                        <li>
                            <strong>Słownie:</strong> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                        </li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 invoice-block">
                    <ul class="list-unstyled amounts">
                        <li>
                            <strong>Uwagi:</strong>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                        </li>
                    </ul>
                </div>
            </div>
            <hr>
            <br style="clear: both;">
            <br>
            <br>
            <div class="row">
                <div class="col-xs-12 invoice-block">
                    <ul class="list-unstyled amounts text-align-center col-sm-2 pull-left">
                        <li>
                            <h4><strong>Marcin Walas</strong></h4>
                        </li>
                        <li>
                            Imię i Nazwisko odbiorcy
                        </li>
                    </ul>
                    <ul class="list-unstyled amounts text-align-center col-sm-2 pull-right">
                        <li>
                            <h4><strong>Marcin Walas</strong></h4>
                        </li>
                        <li>
                            Imię i Nazwisko wystawcy
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>